In [ ]:
#How algorithms are created 

In [3]:
import numpy as np

In [4]:
#Linear Regression
#RScien create algorithms in the form of classes and function in libraires.
#Class(algorithm) can be used to create objects(models)
class LinearRegression:   #linear regression algorithm(Class)
    def __init__(self,learning_rate=0.01,n_iter=1000):  #constructor to initialize value
         #we dont want bias and weights as an argument                
        #we are defining values of alpha and no of iteration bcoz we will pass them as param and use it as an argument
        self.bias= None   #we need bias different for every model,as y-intercept,coeffiicient can be different for every model
                          #therefore we are defining it as object parameter and not class parameter 
                          #also we need to initialize Theta0(bias),Theta1(coeficient/weights) therefore using selfconstructor 
        self.weights=None
        self.lr=learning_rate 
        self.n_iter=n_iter

    def fit(self,X,y):     #fit is an imp func,used for model training,contains setp1,2,3,4
                     #taking self in order to use bias and weights
                      
        #STEP 1 - random initialize
        m,n=X.shape   #(number of samples, number of features)
        self.bias=0
        self.weights=np.zeros(n)  # [0, 0, ..., 0]

        
         # Gradient Descent
        for i in range(self.n_iter):
            # STEP2 - calc y_pred
            y_pred = self.bias + np.dot(X, self.weights)
    
            # STEP3 - calc gradient
            db = (1/m) * np.sum(y_pred - y)
            dw = (1/m) * np.dot(X.T, (y_pred - y))
    
            # STEP4 - convergence theorem - params update
            self.bias -= self.lr * db #theta0
            self.weights -= self.lr * dw  #theta1
   #now we will have updated values of bias and weights after 1000 iterations
    
    def predict(self, X):
        y_pred = self.bias + np.dot(X, self.weights)
        return y_pred #BFL

In [7]:
X = np.array([[1], [2], [3], [4], [5]])
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
y = np.array([2, 4, 6, 8, 10])
y

array([ 2,  4,  6,  8, 10])

In [9]:
model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)

print(model.bias)
print(model.weights)
#bias and weighst should be y=x*2

[2.06850809 4.04226297 6.01601785 7.98977273 9.96352761]
0.09475321533750963
[1.97375488]


In [10]:
# Linear reg with OLS

class LinearRegressionOLS:
    def __init__(self):
        self.bias = None
        self.weights = None

    def fit(self, X, y):
        m, n = X.shape

        X_b = np.c_[np.ones((m, 1)), X]

        # normal equation
        # theta = np.dot( np.linealg.inv(np.dot(X_b.T, X_b)), np.dot(X_b.T, y)) 
        theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

        self.bias = theta[0]
        self.weights = theta[1:]

    def predict(self, X):
        y_pred = self.bias + np.dot(X, self.weights)
        return y_pred


In [11]:
X = np.array([[1], [2], [3], [4], [5]])#means only 1 feature x1
y = np.array([2, 4, 6, 8, 10])

model = LinearRegressionOLS()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)

print(model.bias)
print(model.weights)

[ 2.  4.  6.  8. 10.]
5.329070518200751e-15
[2.]
